name: quiz_u_okoul
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  connectivity_plus: ^3.0.0
  country_icons: ^2.0.2
  country_picker: ^2.0.16
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  freezed: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
