name: quiz_u
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  dio: ^4.0.6
  fl_country_code_picker: ^0.0.3+1
  flutter_hooks: ^0.18.5+1
  flutter_otp_text_field: ^1.1.1
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  google_fonts: ^3.0.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  loading_indicator: ^3.1.0
  phone_number: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
