name: quiz_u_final
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  # framework
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

  # UI
  country_icons: ^2.0.2
  country_picker: ^2.0.16
  flutter_svg: ^1.1.5
  flutter_otp_text_field: ^1.1.1

  # network
  connectivity_plus: ^3.0.0
  dio: ^4.0.6
  analyzer: ^5.1.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  freezed: ^2.2.0

  # Functional Programming
  dartz: ^0.10.1

  # State management
  stacked: ^3.0.0
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  stacked_services: ^0.9.5
  rxdart: ^0.27.5

  # annotations
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Dependency injection
  get_it: ^7.2.0

  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  stacked_generator: ^0.8.0+1

flutter:
  uses-material-design: true
